Min_max_operators
explosion/spaCy pull request #10981
Opened 2022-06-18 07:12 UTC by shen-qin

## Description

Reupload of #10919 
Resolved #5603 

Added min max quantifier {n,m}
![image](https://user-images.githubusercontent.com/82353723/174426573-7a208987-8bae-4a01-93bd-56d61b852597.png)

Summary
1. Modified API and Usage for spaCy website to include min_max operator
2. Modified matcher.pyx to include min_max function {n,m} and its variants
3. Modified schemas.py to include min_max validation error
4. Added test cases to test_matcher_api.py, test_matcher_logic.py and test_pattern_validation.py

### Types of change

Min_max operator {n,m} for matcher
## Checklist

- [x] I confirm that I have the right to submit this contribution under the project's MIT license.
- [x] I ran the tests, and all new and existing tests passed.
- [x] My changes don't require a change to the documentation, or if they do, I've added all required information.

2022-06-20 15:31 UTC, svlandeg commented
Researched the `mypy` failure a bit and updated the branch directly according to [this](https://stackoverflow.com/a/67871116/7961860) advice from StackOverflow.

2022-06-29 08:58 UTC, adrianeboyd requested changes
Very nice PR!

I tried and failed to break the validation. I added some additional bad cases and a suggestion to move these test cases to the section of the list for cases that are always flagged (nothing is technically incorrect).

2022-06-29 15:49 UTC, adrianeboyd approved these changes

2022-06-29 15:53 UTC, shen-qin commented
Nice! Thank you :D

2022-06-30 09:01 UTC, merged