Fix types of Tok2Vec encoding architectures
explosion/spaCy pull request #6442
Opened 2020-11-24 16:42 UTC by svlandeg

This fix is required to resolve https://github.com/explosion/spaCy/issues/6318, together with https://github.com/explosion/thinc/pull/432.

## Description
I think the "encode" architectures were not returning the correct type, and they should incorporate `with_array` themselves instead of relying on `Tok2Vec` to do so. Technically this changes these models, so I've bumped the versions and kept the old ones in the same file (for now).

This was necessary to make `TorchBiLSTMEncoder.v1` function correctly, and I think it's better overall.

Also fixed the documentation of `TorchBiLSTMEncoder.v1` which was referring to wrong parameters.

### Types of change
bug fix + docs fix

## Checklist
- [x] I have submitted the spaCy Contributor Agreement.
- [x] I ran the tests, and all new and existing tests passed.
- [x] My changes don't require a change to the documentation, or if they do, I've added all required information.

2020-12-08 06:46 UTC, honnibal commented
> they should incorporate with_array themselves instead of relying on Tok2Vec to do so. 

I think that isn't quite right, as I think it messes up the padding requirement. If you have a `List[Floats2d]` as input to the `MaxoutWindowEncoder`, you have to take care that you add padding to avoid it reading context from surrounding arrays. So it seems incorrect to add the `with_array` within the layer.

2020-12-08 06:47 UTC, honnibal requested changes
I think moving the `with_array` layer inside probably isn't correct.

2020-12-08 08:44 UTC, svlandeg commented
Hm, ok, thanks, I'll have another look!

2020-12-22 10:17 UTC, svlandeg commented
@honnibal : Hm, I had another look, and I'm not sure I understand what's wrong in this PR :(

The original `v1` implementation of `MaxoutWindowEncoder` seems to be - to me - a `Model[Floats2D, Floats2D]` architecture, and not a `Model[List[Floats2d], List[Floats2d]]` architecture as the type suggests. This encoder does the cloning of the layers according to `depth` within its definition:
```
cnn = chain(expand_window, Maxout)
model = clone(residual(cnn), depth)
return model
```

It is fed as input to `Tok2Vec.v1` which does
```
tok2vec = chain(embed, with_array(encode, pad=receptive_field))
```

My proposal would be, for the `v2` implementation, to add `with_array` just at the end of `MaxoutWindowEncoder`, which means that it's still applied to the whole block and not just layer by layer, no?
```
cnn = chain(expand_window, Maxout)
model = clone(residual(cnn), depth)
return with_array(model, pad=receptive_field)
```
Then the `Tok2Vec.v2` will get an actual encoding architecture of type `Model[List[Floats2d], List[Floats2d]]` and can just do 
```
tok2vec = chain(embed, encode)
```

All this matters because the `BiLSTMEncoder` seems to be (currently) the only encoder that actually returns the correct type ` Model[List[Floats2d], List[Floats2d]]`:
```
return with_padded(PyTorchLSTM)
``` 
 and then if you use that encoder with `Tok2Vec.v1`, you get 
```
tok2vec = embed > with_array(with_padded(PyTorchLSTM))
```
while I think it should just be 
```
tok2vec = embed > with_padded(PyTorchLSTM)
```
?

If I'm entirely wrong - I still think we need to change the types of `spacy.MaxoutWindowEncoder.v1` & `spacy.MishWindowEncoder.v1` AND find another way to fix the combination of `spacy.TorchBiLSTMEncoder.v1`+ `spacy.Tok2Vec.v1` (cf https://github.com/explosion/spaCy/issues/6318)

2021-01-07 05:39 UTC, honnibal commented
Ah sorry, I see what you mean now. My mistake was that I thought the `MaxoutWindowEncoder` layer was doing one CNN, instead of the whole CNN block. It does make sense to give it the `with_array` responsibility.

2021-01-07 05:39 UTC, merged