South African Setswana Language
explosion/spaCy pull request #7011
Opened 2021-02-10 18:26 UTC by Shumie82

## Description

### Types of change

## Checklist

- [ ] I have submitted the spaCy Contributor Agreement.
- [ ] I ran the tests, and all new and existing tests passed.
- [ ] My changes don't require a change to the documentation, or if they do, I've added all required information.

2021-02-10 18:43 UTC, Shumie82 commented
Please approve the additional of South African Setswana language to your repository. Thanks

2021-02-10 20:53 UTC, svlandeg requested changes
Thanks for the PR! It would definitely be good to have support for Setswana in spaCy!

I've added a few detailed comments and suggested changes. You should be able to just accept these changes on the Github interface (if you agree with them, ofcourse).

One other question I have is whether you could include a few unit tests that showcase that the processing of a Setswana text goes ok. The tests are stored at `spacy/tests/lang`. https://github.com/explosion/spaCy/blob/master/spacy/tests/lang/ti/test_text.py is a good example: a few tests to check that a sentence is segmented in the correct number of words, and a test that checks whether the `like_num` property works as expected for a variety of Setswana words. It would be great if you could add some tests like those!

2021-02-10 20:53 UTC, svlandeg commented on spacy/lang/tn/__init__.py
> +    suffixes = TOKENIZER_SUFFIXES
I think you want to do this instead?
```suggestion
    infixes = TOKENIZER_INFIXES
```

2021-02-10 20:53 UTC, svlandeg commented on spacy/lang/tn/examples.py
> +
You can just remove these lines - they were only relevant when we were still supporting Python 2
```suggestion
```

2021-02-10 20:53 UTC, svlandeg commented on spacy/lang/tn/lex_attrs.py
> +
You can just remove these lines - they were only relevant when we were still supporting Python 2
```suggestion
```

2021-02-10 20:53 UTC, svlandeg commented on spacy/lang/tn/stop_words.py
> +
You can just remove these lines - they were only relevant when we were still supporting Python 2
```suggestion
```

2021-02-10 20:53 UTC, svlandeg commented on spacy/lang/tn/stop_words.py
> +print(STOP_WORDS)
```suggestion
```

2021-02-10 20:53 UTC, svlandeg commented on spacy/lang/tn/examples.py
> +>>> from spacy.lang.en.examples import sentences
```suggestion
>>> from spacy.lang.tn.examples import sentences

```

2021-02-11 19:43 UTC, Shumie82 commented
Thanks Sofie for the comments and review.  Please review the changes I have made.
For the tests, I will submit another pull request as soon as I am done. Just to make sure I have checked all that needs to be done properly. 
Thanks.

2021-02-13 01:30 UTC, ines commented
Thanks so much for your work on this 👍 I made one small update and all tests are green now. I'll go ahead and merge this PR. You can then submit another pull request with some tests whenever you're ready.

2021-02-13 01:30 UTC, ines approved these changes

2021-02-13 01:30 UTC, merged