Update universe.json
explosion/spaCy pull request #8593
Opened 2021-07-04 00:14 UTC by yohasebe

## Description
- ruby-spacy, ruby wrapper for spaCy, is added to Non-Python section of spaCy Universe

### Types of change
- added entry for ruby-spacy to [universe.json]

## Checklist
- [x] I have submitted the spaCy Contributor Agreement.
- [x] I ran the tests, and all new and existing tests passed.
- [x] My changes don't require a change to the documentation, or if they do, I've added all required information.

2021-07-04 09:41 UTC, polm requested changes

2021-07-04 09:41 UTC, polm commented on website/meta/universe.json
> +            "github": "https://github.com/yohasebe/ruby-spacy",
This should be `yohasebe/ruby-spacy` in order to show up correctly.

2021-07-04 09:42 UTC, polm commented
Thanks for the PR, spacy-ruby looks like a cool project! 

There's one small detail of your JSON that should be fixed but other than that it looks good.

2021-07-04 09:58 UTC, yohasebe commented
Thank you for pointing it out! I fixed the github repository info.

2021-07-05 01:31 UTC, ines approved these changes

2021-07-05 01:31 UTC, merged