Move WandB loggers into spacy-loggers
explosion/spaCy pull request #9223
Opened 2021-09-15 22:00 UTC by rspeer

This PR depends on https://github.com/explosion/spacy-loggers being published.

## Description
Move the Weights & Biases logger into `spacy-loggers`, a new dependency of spaCy.

## Checklist

- [x] I confirm that I have the right to submit this contribution under the project's MIT license.
- [ ] I ran the tests, and all new and existing tests passed.
- [x] My changes don't require a change to the documentation, or if they do, I've added all required information.

(Tests are not currently passing for me on develop, but I figured I would get this PR started.)

2021-09-16 10:41 UTC, adrianeboyd requested changes

2021-09-16 10:41 UTC, adrianeboyd commented on requirements.txt
> +spacy-loggers>=1.0,<2.0
Just for consistency:

```suggestion
spacy-loggers>=1.0.0,<2.0.0
```

2021-09-16 10:41 UTC, adrianeboyd commented on setup.cfg
> +    spacy-loggers>=1.0,<2.0
```suggestion
    spacy-loggers>=1.0.0,<2.0.0
```

2021-09-24 15:49 UTC, svlandeg commented on website/docs/api/top-level.md
> -#### spacy.WandbLogger.v2 {#WandbLogger tag="registered function"}
I'm guessing that this anchor point `#WandbLogger` is being referred to from other places of the docs too, and we'll need to update those too. Perhaps we can make sure that https://github.com/explosion/spacy-loggers#wandb or something such is a valid URL point to the latest `WandbLogger` implementation, then update the links through the docs?

We'll also need to update comments like "There are two built-in loggers" --> one built-in, with alternatives defined in https://github.com/explosion/spacy-loggers, etc.

2021-09-27 09:19 UTC, adrianeboyd commented
This will need to updated following #9296 to remove the v3 logger cleanly, too.

2021-09-27 11:31 UTC, svlandeg commented
I'll just put this in draft for now - @rspeer feel free to take it back out of draft when you're ready!

2021-09-28 23:16 UTC, svlandeg approved these changes
Looks good to me! :-)

2021-09-29 09:12 UTC, adrianeboyd approved these changes

2021-09-29 09:12 UTC, merged